# Generated by Django 4.2.5 on 2023-09-22 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOptions',
            fields=[
                ('id_answerOption', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id_application', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id_criteria', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id_property', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QualityProfiles',
            fields=[
                ('id_qualityProfile', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('custom', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualityProfileCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.criteria')),
                ('quality_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.qualityprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.applications')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id_evaluation', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('result', models.CharField(max_length=255)),
                ('final_score', models.FloatField()),
                ('vis_file', models.FileField(upload_to='evaluations/')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.answeroptions')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.evaluations')),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.criteria')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.properties')),
            ],
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='id_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.applications'),
        ),
    ]
