# Generated by Django 4.2.5 on 2023-09-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_evaluation_alter_evaluationansweroption_evaluation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerOptions',
            new_name='AnswerOption',
        ),
        migrations.RenameModel(
            old_name='Properties',
            new_name='Application',
        ),
        migrations.RenameModel(
            old_name='Applications',
            new_name='Propertie',
        ),
        migrations.RenameModel(
            old_name='QualityProfiles',
            new_name='QualityProfile',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='id_property',
            new_name='id_application',
        ),
        migrations.RenameField(
            model_name='propertie',
            old_name='id_application',
            new_name='id_property',
        ),
    ]
