# Generated by Django 4.2.5 on 2023-09-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_answeroptions_answeroption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='id_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.application'),
        ),
        migrations.AlterField(
            model_name='criteriaproperties',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.propertie'),
        ),
        migrations.AlterField(
            model_name='propertiesapplications',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.application'),
        ),
        migrations.AlterField(
            model_name='propertiesapplications',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.propertie'),
        ),
    ]
